### ISSUE TITLE
jest-haste-map: @providesModule naming collision:

### ISSUE THREAD

**Issue by kcfgl** [mfrachet/rn-placeholder#10]
Really looking forward to using this library, looks awesome. But I'm getting a naming collision when I install.

I'm on RN@44.3

```
This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: .../node_modules/react-native/package.json collides with /.../node_modules/rn-placeholder/node_modules/react-native/package.json
```
What is the best way to fix this issue? Thanks.

**Comment by mfrachet** [comment]
Hi, and thanks for the kind words :D

This isssue is known here : https://github.com/mfrachet/rn-placeholder/issues/5

Can you tell me if you can reproduce it by cleaning NPM and running on a v0.44.0 react native project ?

I'll take a look on tomorrow, maybe moving react native to dev dependencies may solve the issue...

Thanks for your interest by the way :)

**Comment by mfrachet** [comment]
Hey :)

Before I merge, can you tell me if using the following dependency solved your issue ? 

```
"rn-placeholder":"mfrachet/rn-placeholder#eb1848f"
```

It will take a specific commit where I have moved the react native dependency inside of the dev dependencies.

It works for me locally, so your feedback would be really appreciated 👍 

Thanks for your help :)

**Comment by kcfgl** [comment]
Hey Marvin - I can check it out in a few hours. I'll let you know. And thanks for the quick work to address this!

**Comment by kcfgl** [comment]
@mfrachet I can confirm that I was able to install without any errors or warnings - even on @44.3

**Comment by mfrachet** [comment]
Super cool, let's merge, and publish 0.0.7 :D
