### ISSUE TITLE
RN Placeholder import is undefined RN 0.60.5

### ISSUE THREAD

**Issue by gabrielbuzziv** [mfrachet/rn-placeholder#104]
When importing the package like `import Placeholder from 'rn-placeholder'` is comming as undefined, for a reason a don`t know why.

![RN Placeholder import error](https://i.imgur.com/aekcTSO.png)

I just installed following the installations steps

`yarn add rn-placeholder` and  is not being able to import.

```
"react": "16.8.6",
"react-native": "0.60.5",
"rn-placeholder": "^3.0.0"
```

**Comment by mfrachet** [comment]
Since V3, Placeholder is a named import and thus should be used like:

`import { Placeholder } from 'rn-placeholder'` 😊

**Comment by mfrachet** [comment]
I'm closing this for now, feel free to reopen

**Comment by gabrielbuzziv** [comment]
@mfrachet Thanks for answering. 
I've tried this way too, but then i get another error, maybe the way to create Custom Component changed and is not documented correctly.

```
import React from 'react';

import { View } from 'react-native';
import { Placeholder } from 'rn-placeholder';

function Product() {
  return (
    <View style={styles.container}>
      <View style={styles.image} />

      <View style={styles.title} />
      <View style={styles.price} />
    </View>
  );
}

export default Placeholder.connect(Product);
```

Got the message below.

![Error](https://i.imgur.com/tN9XbXV.jpg?1)

**Comment by gabrielbuzziv** [comment]
I can`t reopen the issue since you closed, but i hope you see it @mfrachet

**Comment by mfrachet** [comment]
I think that you're trying to use the v1 or v2 API but you're using the v3 version in your dependencies 😄 . I suggest you check https://github.com/mfrachet/rn-placeholder README for the v3 usage.

I'm also rebuilding the website with some explanations. It should be available for documentation in the week

**Comment by gabrielbuzziv** [comment]
Hmm, thats it, thanks
