### ISSUE TITLE
Custom fade backgroundColor

### ISSUE THREAD

**Issue by karanpratapsingh** [mfrachet/rn-placeholder#109]
https://github.com/mfrachet/rn-placeholder/blob/26feb7a47cd67baa92373e5c67fc631edf0b5474/src/animations/Fade.tsx#L27

first of all amazing library, have used it production for some time but is it possible to customize this via props? I would really like that functionality as I need to make it a little darker in dark mode

Thanks @mfrachet

**Comment by mfrachet** [comment]
I think you can achieve that without an extra prop nope? https://snack.expo.io/BJYelnc2H

Let me know if it helps 😊

**Comment by karanpratapsingh** [comment]
@mfrachet thanks for the response. how can I achieve that? the snack doesn't contain anything, it just shows `hello`

**Comment by karanpratapsingh** [comment]
okay I figured it out if anyone runs into this problem, here's the solution

use this:
```
Animation{props => <Fade {...props} style={{ backgroundColor }} />}
```
rather than:
```
Animation{Fade}
```

**Comment by mfrachet** [comment]
Oh sorry ! I didn't linked to the good one 🤦‍♂ . Happy you've found the solution and sorry for this out of range answer I've provided

**Comment by karanpratapsingh** [comment]
no issues mate, happens 😄
