### ISSUE TITLE
Not working if wrapped under flexDirection: row

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [mfrachet/rn-placeholder#112]
Not working if wrapped under flexDirection: row. The content is blank if wrapped with flexDirection. Please provide solution to have multiple placeholder in a single row.

**Comment by ManigandanRaamanathan** [comment]
@mfrachet

**Comment by ManigandanRaamanathan** [comment]
this is my code 
`<View style={{flexDirection: 'row}}>
            <Placeholder  Animation={ShineOverlay}>
                <PlaceholderLine width={wp(12.1)} height={wp(32)} style={{borderRadius: wp(2), marginBottom: wp(2)}} />
                <PlaceholderLine width={wp(11)} style={{marginBottom: wp(2)}} />
                <PlaceholderLine width={wp(9)} style={{marginBottom: wp(1.5)}} />
                <PlaceholderLine width={wp(6)} height={wp(1.5)} />
                <PlaceholderLine width={wp(8)} height={wp(1.5)} />
            </Placeholder>

            <Placeholder  Animation={ShineOverlay}>
                <PlaceholderLine width={wp(12.1)} height={wp(32)} style={{borderRadius: wp(2), marginBottom: wp(2)}} />
                <PlaceholderLine width={wp(11)} style={{marginBottom: wp(2)}} />
                <PlaceholderLine width={wp(9)} style={{marginBottom: wp(1.5)}} />
                <PlaceholderLine width={wp(6)} height={wp(1.5)} />
                <PlaceholderLine width={wp(8)} height={wp(1.5)} />
            </Placeholder>
        </View>`

**Comment by mfrachet** [comment]
Hey thanks for pointing this :blush: . Can you provide a snack repro so that I can play with it and check what's going wrong?

Thank you 😊 

https://snack.expo.io/

**Comment by ManigandanRaamanathan** [comment]
@mfrachet here you go https://snack.expo.io/B1gsGu!f8 
The snack rendering only 1 placeholder instead of 2 placeholders thats in the view

**Comment by mfrachet** [comment]
Do you have something you want to achieve particularly?

I've tried adding "flex: 1" on both of the placeholders and they are on the same line.

What's the expected behaviour?

**Comment by ManigandanRaamanathan** [comment]
I want to display multiple placeholders in a flexDirection: row

**Comment by mfrachet** [comment]
Is that what you want? https://snack.expo.io/HJk!t_jG8

**Comment by ManigandanRaamanathan** [comment]
@mfrachet yes. Thanks for the update. Will try and let you know
