### ISSUE TITLE
Animation not work in Android

### ISSUE THREAD

**Issue by CarmeloXue** [mfrachet/rn-placeholder#113]
I use this as a Skeleton, it works well in IOS, but the Animation just not work in android device (android version 7.1.1). 

` <Placeholder Animation={ShineOverlay}>
          <View style={styles.short80}>
            <PlaceholderLine height={px2dp(8)}></PlaceholderLine>
          </View>
        </Placeholder>
`

**Comment by mfrachet** [comment]
Can you provide a snack reproduction so that I can play with it and check what's going wrong? 😊 

Thank you :D

**Comment by ameer-taghavi** [comment]
also `ShineOverlay` animation is not working in `android` for me

**Comment by mfrachet** [comment]
@ameer-taghavi can you provide a snack repro of this please?
