### ISSUE TITLE
Graphs

### ISSUE THREAD

**Issue by joaonew** [mfrachet/rn-placeholder#118]
Hello, I'm just wondering if it would be possible to use this lib to put a placeholder on top of a graph while it is being rendered, and if so, if there is any example code that I could take a look?

Thanks.

**Comment by mfrachet** [comment]
Well, it will depend on the way you use your graph :) but you can potentially do something like:

```jsx
const App = () => (
<View>
  {!chartLoaded && <Placeholder
    Animation={Fade}
    Left={PlaceholderMedia}
    Right={PlaceholderMedia}
  >
    <PlaceholderLine width={80} />
    <PlaceholderLine />
    <PlaceholderLine width={30} />
  </Placeholder>}

<Chart onFinishLoading={changeStateToHidePlaceholder} />
</View>
);
```
