### ISSUE TITLE
Animated: "useNativeDriver" was not specified warning

### ISSUE THREAD

**Issue by NelsonPRSousa** [mfrachet/rn-placeholder#120]
Just updated to React Native 0.62.2 and there's a warning using `rn-placeholder` library, version 3.0.0.

`Animated: useNativeDriver was not specified. This is a required option and must be explicitly set to true or false`

Code:
```javascript
<Placeholder Animation={ShineOverlay}>
(...)
</Placeholder>
```

Should we add this property to ShineOverlay component?

**Comment by NelsonPRSousa** [comment]
@mfrachet any news regarding this issue?

**Comment by mfrachet** [comment]
I will try to take a look on tomorrow. It's probably because I don't explicitly set `useNativeDriver` in the animations. Nothing too critical but I need to tweak a little my computer to have all the ios and android things running before fixing 😊

**Comment by mfrachet** [comment]
This should be fixed in v3.0.1. Let me know if it still doesn't work for you :)

**Comment by NelsonPRSousa** [comment]
Tested with 3.0.1. It's working as before without the warning 👍 

Thank you 🚀

**Comment by tranvanquang** [comment]
Tested with 3.0.1. It's not working, I still received a warning.!!! how can I add useNativeDriver on rn-placeholder. And if u using version 3.0.1 working. Can u show me a demo !!!

**Comment by nelsonprsousa** [comment]
@tranvanquang Make sure you are not receiving that warning from some other component. I am using 3.0.1 without that warning.
