### ISSUE TITLE
Warning: Animated: `useNativeDriver` was not specified

### ISSUE THREAD

**Issue by tranvanquang** [mfrachet/rn-placeholder#122]
I receive a warning:
Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false` 
When I using 
<Placeholder Animation={ShineOverlay} />
If I remove Animation={ShineOverlay} I will no see warning. How can I help me using useNativeDriver and Animation={ShineOverlay} together. 

"rn-placeholder": {
      "version": "3.0.0"
    },

**Comment by mfrachet** [comment]
Thanks for reporting !

In the future, please take time to verify the existing issue, there's already one dealing with this 😊  
https://github.com/mfrachet/rn-placeholder/issues/120

I'm closing and will continue on #120
