### ISSUE TITLE
The example/storybook/stories/animations.tsx has imported "../../placeholder", but it not exists

### ISSUE THREAD

**Issue by yibingxiong** [mfrachet/rn-placeholder#141]
The example/storybook/stories/animations.tsx has imported "../../placeholder", but the file not exists.
so when I run, an exception occured. Like 'Unable to resolve "../../placeholder" from "storybook/stories/animations.tsx"' @mfrachet

**Comment by mfrachet** [comment]
Did you manage to fix this? 😊
