### ISSUE TITLE
_react. Default. useEffect is not a function

### ISSUE THREAD

**Issue by Mr-nan** [mfrachet/rn-placeholder#144]
Error running React-Native reporting "_react. Default. useEffect is not a function"

**Comment by Mr-nan** [comment]
![Uploading 61604916322_.pic.jpg…]()

**Comment by Mr-nan** [comment]
![WechatIMG6](https://user-images.githubusercontent.com/17428078/98527736-5a576000-22b6-11eb-8dfb-e31a5ecd8917.jpeg)

**Comment by mfrachet** [comment]
Which version of react and react native are you using?

**Comment by mfrachet** [comment]
No answer from ~1 month. I'm closing, feel free to reopen if needed.
