### ISSUE TITLE
bug: Error occurs in android when set PlaceholderLine's width by percent

### ISSUE THREAD

**Issue by ameer-taghavi** [mfrachet/rn-placeholder#147]
`<PlaceholderLine width="30%" />`

<img width="411" alt="image" src="https://user-images.githubusercontent.com/12966060/103762702-ff2fb880-502d-11eb-8afe-4c77e269ba9a.png">

**Comment by mfrachet** [comment]
Can you provide a https://snack.expo.io/ repro of this please?

**Comment by ameer-taghavi** [comment]
> Can you provide a https://snack.expo.io/ repro of this please?

https://snack.expo.io/@ameer/83cd3b

**Comment by kyamashiro** [comment]
You should replace `<PlaceholderLine width="30%" />` to `<PlaceholderLine width={30} />`  and it'll work.

**Comment by ameer-taghavi** [comment]
Does the number convert to percentage?

**Comment by kyamashiro** [comment]
https://github.com/mfrachet/rn-placeholder/blob/75f352c5b882fcd4b20aac641b514cdce2741b58/src/PlaceholderLine.tsx#L11-L12

It looks like it.

**Comment by mfrachet** [comment]
Sorry for being late, yes, it converts :)

**Comment by mfrachet** [comment]
I'm closing the issue for now since it looks resolved, feel free to reopen. And thank you @kyamashiro for your help here 🙏🏻
