### ISSUE TITLE
Option to change the default Animation background color

### ISSUE THREAD

**Issue by benjaminfiliatrault** [mfrachet/rn-placeholder#151]
It would be useful to use that feature especially when trying to implement a dark theme where the placeholder background should not be white but darkish. I looked out the Fade.js file and the value is hard coded

![image](https://user-images.githubusercontent.com/37634960/111081502-0239a000-84da-11eb-837d-6dc597087aef.png)

Using color on, for example, PlaceholderMedia we can set a color but then the fade varies from backgroundColor: "#dfdfdf" ( the hard coded one) to the color set on the PlaceholderMedia.

**Comment by idanlevi1** [comment]
> It would be useful to use that feature especially when trying to implement a dark theme where the placeholder background should not be white but darkish. I looked out the Fade.js file and the value is hard coded
> 
> ![image](https://user-images.githubusercontent.com/37634960/111081502-0239a000-84da-11eb-837d-6dc597087aef.png)
> 
> Using color on, for example, PlaceholderMedia we can set a color but then the fade varies from backgroundColor: "#dfdfdf" ( the hard coded one) to the color set on the PlaceholderMedia.

Did you find any solution?
