### ISSUE TITLE
Add useNativeDriver to improve performance

### ISSUE THREAD

**Issue by calvinmikael** [mfrachet/rn-placeholder#32]
Hello, thank you for this wonderful module. I believe there are a couple lines of code that can be added to this project that will significantly speed up the performance for most use cases without any backwards incompatible changes to the code base. The single caveat being that you may have to limit support for the next version of the module to version >=0.40 of React Native. I can easily submit a PR for this if desired (just tell me if there are specific conventions such as commit message policies).

Docs from Facebook:
https://facebook.github.io/react-native/blog/2017/02/14/using-native-driver-for-animated.html

Example from competing module:
https://github.com/zeljkoX/react-native-loading-placeholder/commit/05b4cd6483309271e5d8d820d5fb0eb0b81c864e

**Comment by mfrachet** [comment]
Hey :D 

I'm happy you like the module :)

The idea seems interesting. I've created a PR (https://github.com/mfrachet/rn-placeholder/pull/33) concerning the [fade](https://github.com/mfrachet/rn-placeholder/blob/master/src/animation/fade.js) animation (that relies on opacity and that can be managed from the native lands)

For now, I can't apply this to the [shine](https://github.com/mfrachet/rn-placeholder/blob/master/src/animation/shine.js) animation that relies on a `marginLeft` style transitions.

Maybe more investigations / refacto of the shine animation to use `transform` style property could be a good idea :). ([see this](https://facebook.github.io/react-native/blog/2017/02/14/using-native-driver-for-animated.html#caveats) for more information concerning `useNativeDriver` caveats)

**Comment by calvinmikael** [comment]
Thank you for the quick response and good catch with the caveats section, I'll be sure to update and use the new version soon.

**Comment by mfrachet** [comment]
Closed with https://github.com/mfrachet/rn-placeholder/pull/33
