### ISSUE TITLE
Allow for passing in arbitrary styles

### ISSUE THREAD

**Issue by conrad-vanl** [mfrachet/rn-placeholder#38]
Would there be any interest for a PR that added the feature to be able to pass in arbitrary styles to placeholders? We've found the built-in props for a few of our use cases to be limiting, especially for fine-tuning the positioning of placeholder elements. We'd hate to wrap the placeholders in additional views, so we're left with having to build custom placeholders. However, if these components allowed for passing in arbitrary styles for more control, we'd be able to solve for our use case.

I'm happy to open a PR if there's interest. 

```jsx
<Box style={...} />
<ImageContent style={...} paragraphStyle={...} mediaStyle={...} />
<Line style={...} />
<Media style={...} />
<MultiWords style={...} wordStyle={...} />
<Paragraph lineStyle={...} style={...} />
```

**Comment by burkeshartsis** [comment]
A great example of this was with needing a `Placeholder.Media` or `Placeholder.Box` that respected aspect ratio. This is trivial if you can pass in the `aspectRatio` style prop but the current components don't allow for that.

Positioning typography components as mentioned @conrad-vanl is also unnecessarily brittle. Requiring a wrapper component, and handful of duplicated styles.

Love the library and where it's headed. A style prop seems like an obvious add to me.

**Comment by mfrachet** [comment]
This sounds to be a good idea 😄

**Comment by mfrachet** [comment]
Let me know if you would like to take the point or if I create a pull request from my side 😄

**Comment by conrad-vanl** [comment]
Hey @mfrachet! Apologies, since writing the first message, my wife and I gave birth to our first son, and so I've been away from work for a while. I had started this work in this branch before - https://github.com/conrad-vanl/rn-placeholder/tree/style-prop

I believe this _might_ be pull-requestable, and happy to go ahead and open if you like. But might need a little more polish as well.

**Comment by mfrachet** [comment]
Congrats to you and your wife 😄  I wish you all the best ! 

Don't worry, take time to rest and enjoy life. I will take some time to check what you've made and probably open something.

If you prefer to open the PR, I would be happy to help you on it :). Else, I'll make it mentioning your investment on the topic 😄 

Have a great week end and again, congratulations 🎉

**Comment by jaulz** [comment]
Could anyone spend some time on this? :-)

**Comment by mfrachet** [comment]
I'm currently working on, here's the current state:

- [ ] `<Box style={...} />`
- [ ] `<ImageContent style={...} paragraphStyle={...} mediaStyle={...} />`
- [x] `<Line style={...} />`
- [ ] `<Media style={...} />`
- [ ] `<MultiWords style={...} wordStyle={...} />`
- [ ] `<Paragraph lineStyle={...} style={...} />`

**Comment by luweiCN** [comment]
I am wondering how is it going? I am having this issue too. I just roughly edit the `node_modules` code to solve the problem. I hope these feature will be supported officially soon.
``` 
// placeholderContainer.js
const renderAnimation = (Animation, Component, props) => {
  if (!Animation) {
    throw new Error(`${Animation.name} doesnt exist in the current project`);
  }
  return (
    <Animation style={props.style}>
      <Component {...props} />
    </Animation>
  );
};
```
```
// animation/fade.js
return <Animated.View style={[style, { opacity: animation }]}>{children}</Animated.View>;
```

**Comment by mfrachet** [comment]
Hello @luweiCN 😊 

This issue concerns the different primitives of the app: it means that I will / would probably work on adding custom styles only on the different primitives of the app.

The part you're describing is not part of this issue for now. If you need some specific behaviours concerning the animation part, you can create your own one using https://mfrachet.github.io/rn-placeholder/customize/animation.html

I hope this answer is not frustrating to your side and would be happy to discuss a bit more on a way to make the style passing between components more easy 😞

**Comment by mfrachet** [comment]
I'm sorry for being that late dealing this issue, my new job doesn't really for open source work some hours a week so...

But I think that I come with a solution that would help this library being simpler (in term of tree level) more customizable and composable: compound components.

Let's image a V2 that would look like:

```javascript
const Component = () => (
  <Placeholder onReady={this.state.isReady} animate="fade">
     <Media position="left" />
     <Line width="80% />
     <Line width="30% />
  </Placeholder>
)
```

It would allow to customize the component style directly without passing props down the tree

It would allow to create custom patterns for line and (potentially) to animate any element depending the developer needs.

With this approach, I'm also looking at a way to make the animation better without the effect it has for now (today, animation is clearly a trick)

**Comment by andyr6381** [comment]
Hi thanks for the module, I'm a bit confused on the above but. 

Is it possible to change the backgroundcolor and width of the shine without creating a custom component? The current shines doesn't work for dark themes. I can modify the shine.js to get what I need but can I pass these styles from the component?

const styles = StyleSheet.create({
  shine: {
    width: 30,
    position: 'absolute',
    height: '100%',
    width: '100%', - changed
    backgroundColor: 'black' - changed
    opacity: 0.4,
  },
});

**Comment by mfrachet** [comment]
Yes, the actual shine animation is a tweak, as mentioned above. I think that for dark themes, you should make the color over the animation darker than the line color. It should make something better with this.

**Comment by mfrachet** [comment]
I've been working on a v2 for the library that is actually evolving here: 

https://github.com/mfrachet/rn-placeholder/tree/compound

This should allow to customize a bit more the placeholders and passing styles at the level we want.

Concerning the placeholder on darkmode, I may have some ideas. But it will probably take some time to investiguate 😓

**Comment by mfrachet** [comment]
I close this issue concerning the style passing since composition has been shipped in v2 (https://github.com/mfrachet/rn-placeholder/tree/v2.0.0)

Feel free to reopen if you need more informations 😊
