### ISSUE TITLE
Placeholder.Media repeat and some requests

### ISSUE THREAD

**Issue by Angelk90** [mfrachet/rn-placeholder#39]
@mfrachet : 
Hi, how can I have a series of Placeholder.Media next to each other for a number of repeating columns.

As if it were loading a series of images.

It would be possible to set for Placeholder.Media, in a personalized way:
- height
- length
- personalized border radius

**Comment by mfrachet** [comment]
I think you can achieve this by using the `Box` component : https://github.com/mfrachet/rn-placeholder/blob/master/API.md#box

I just realized that I've not updated the gitbook yet. Something I should definitely do 😅 

Let me know if it's helpful for your need 😄 

Concerning personalised border radius, it's quite related to https://github.com/mfrachet/rn-placeholder/issues/38

**Comment by Angelk90** [comment]
@mfrachet : But how can I repeat a series of boxes next to each other, for a series of lines?

**Comment by mfrachet** [comment]
I'm pretty sure it would have worked using the standard style system 🤔 . Can you show me what you've tried and why it didn't worked ?

Thank you 😊

**Comment by Angelk90** [comment]
@mfrachet : 
What I said, I wanted to make this effect, but that it is synchronized: https://snack.expo.io/BJ7AWyI8M
But I would not want to cycle the elements, I was wondering if there is a way you already do with Placeholder.Paragraph, where you can define the lineNumber.
it would be a very useful thing to define the number of rows and columns, that is, the number of elements that are repeated.

P.Š.
See this effect: https://snack.expo.io/ryuhWJL8M

**Comment by mfrachet** [comment]
Oh, I've got the point :)

It's not possible using the default components, and I m not sure it could take place inside the lib. The lib aims to provide the simplest way of creating placeholders.

However, you could be able to achieve this by using a custom component https://github.com/mfrachet/rn-placeholder/blob/master/API.md#custom

The idea is to remove, from your snack, the `animate` props of your `Placeholder.Box`, and use it in your top level (custom) components.

**Comment by mfrachet** [comment]
@Angelk90  Did you manage to make it work on your project ? :)
