### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by carol-zhao** [mfrachet/rn-placeholder#41]
It works great! but it doesn't have a license file yet, is there a plan to add license file to this rep? Someone may have concern to use it in their product without a clear license declaration.

**Comment by mfrachet** [comment]
It's not mentioned, and I should probably (certainly 😇 ) add the MIT licence in a markdown.

Thanks you for the report 😄

**Comment by mfrachet** [comment]
Fix in https://github.com/mfrachet/rn-placeholder/pull/42
