### ISSUE TITLE
Cannot center Line in  View?

### ISSUE THREAD

**Issue by nagacoder** [mfrachet/rn-placeholder#62]
i want to create Line  centered in my View element, this my code

`<View style={{`
`width: '50%',`
`backgroundColor: 'red',`
`justifyContent: 'center',`
`alignItems: 'center'`
`}}>`
`<Placeholder.Line`
`position='right'`
`color="#efefef"`
`width="30%"`
`/>`
`</View>`

**Comment by ms4ever7** [comment]
```
<View style={styles.placeholderWrapper}>
          <Placeholder.Media
            size={65}
            color='#F2F2F2'
            hasRadius={false}
          />
          <View style={{ height: 5 }} />
          <Placeholder.Paragraph
            animate='shine'
            hasRadius={false}
            lineNumber={2}
            textSize={12}
            lineSpacing={8}
            color='#F2F2F2'
            lastLineWidth='80%'
            firstLineWidth='50%'
          />
        </View>
```
here is for what I would like to center content, can someone help me with that issue? @mfrachet

**Comment by mfrachet** [comment]
I'm really interested in a snack owning all of the different style definition. I'm pretty sure that the problem relies on the "container" around (or in the implementation I've made in this lib on some style properties 😅 )

**Comment by mfrachet** [comment]
It has been a while without this thread to be active. I'm closing it, feel free to reopen with a **snack reproduction** so that I can take a look 😊 

Have a nice day and a wonderful year!

**Comment by adirzoari** [comment]
@ms4ever7  same issue. did you find solution?

**Comment by heliojuniorkrogerbagy** [comment]
> @ms4ever7 same issue. did you find solution?

i just used alignSelf: 'center', and it worked!
