### ISSUE TITLE
require cycle

### ISSUE THREAD

**Issue by kala888** [mfrachet/rn-placeholder#65]
"react": "16.6.1",
    "react-native": "0.57.7",
    "rn-placeholder": "^1.3.0",

![image](https://user-images.githubusercontent.com/1215976/49427167-9980fa80-f7dd-11e8-9a25-7e77a2d4b190.png)

**Comment by mfrachet** [comment]
I think it has been merge right there: https://github.com/mfrachet/rn-placeholder/pull/61

I'm going to make a release soon when merging the next background color on shine.

Thanks for the feedback

**Comment by kala888** [comment]
@mfrachet Thanks，waiting for your latest release....

**Comment by mfrachet** [comment]
The fix has been published under the `1.3.2` version 😊
