### ISSUE TITLE
Typescript definition for Placeholder.connect doesn't expect any arguments

### ISSUE THREAD

**Issue by patgeek** [mfrachet/rn-placeholder#68]
So based on the docs for custom components (https://mfrachet.github.io/rn-placeholder/customize/component.html) the connect function should take in a component as a parameter, but the Typescript definition for the function expects 0 arguments instead of the 1. Is this a mistake in the type definition?

**Comment by mfrachet** [comment]
It's probably a mistake 😓 . Feel free to open a PR to fix this if you want 😊

**Comment by patgeek** [comment]
I'll give it a shot!
