### ISSUE TITLE
Placeholder.ImageContent not working

### ISSUE THREAD

**Issue by vikrampunchh** [mfrachet/rn-placeholder#71]
<Placeholder.ImageContent
				position="right"
				hasRadius
				lineNumber={5}
				textSize={14}
				lineSpacing={5}
				color="#00ff00"
				onReady={false}
				width="100%"
				lastLineWidth="30%"
				firstLineWidth="10%"
			/>

**Comment by mfrachet** [comment]
Can you provide a snack reproduction?

**Comment by mfrachet** [comment]
I've released the v2.0.0. I close this for now. If you face this problem again, let's try to reproduce this on https://snack.expo.io/ so that I can figure out what's going wrong 😊 

Thanks to you and feel free to reopen in case it still doesn't work
