### ISSUE TITLE
Finding a better way to manage animations

### ISSUE THREAD

**Issue by mfrachet** [mfrachet/rn-placeholder#73]
Today animations rely on a trick: a box is put over all of the placeholder components and is animated:

This can cause problem when the user switches the background color or the element colors:

![](https://user-images.githubusercontent.com/3874873/49576297-15498700-f945-11e8-81d2-cdfb9f7b4298.gif)

Does anybody have an idea how we can fix this? 😊

**Comment by asherccohen** [comment]
Is there a known issue regarding animations on Android?It appears to me that emulator doesn't show the animation. Maybe just a performance issue?

**Comment by mfrachet** [comment]
Nope, I wasn't aware about this. Is it possible for you to provide a snack reproduction so that I can verify this? 😊

**Comment by username199327** [comment]
i have this issue too but on my case it was having elevation to the view, it doesnt animate the "shine" effect
but if i remove the elevation style it works again, still looking the issues page to see if there are any similar issues on this

**Comment by mfrachet** [comment]
For the V3, I've taken the part of keeping the actual `Shine` animation which will be called "ShineOverlay" and to add a new Shine animation.

The new one will be a bit different (and a bit less esthetic... I don't have the perfect solution).

I'll post on this issue when I will push the v3-alpha branch 😊

**Comment by mfrachet** [comment]
v3-alpha is on github :D https://github.com/mfrachet/rn-placeholder/pull/86

**Comment by mfrachet** [comment]
This is super complex for the `Shine` animation since it would be needed to have a synchronization between the animation of the elements. For example, for a component like:

```jsx
<Placeholder
    Animation={Shine}
    Left={PlaceholderMedia}
    Right={PlaceholderMedia}
  >
    <PlaceholderLine width={80} />
    <PlaceholderLine />
    <PlaceholderLine width={30} />
  </Placeholder>
```

We would have to:

- start the animation on the left Media component
- when it has finished on the left Media, start on the block of lines
- when it has finished on the block of lines, start the right media
- repeat

**Comment by AbanoubNassem** [comment]
is it possible to use `react-native-reanimated` instead for better smooth/performante animations ?

**Comment by dsznajder** [comment]
@mfrachet I could help with `reanimated` implementation but I'm not sure if you would like to add it as peer dependency.

**Comment by brooksbecton** [comment]
`react-native-reanimated` requires 'react-native linking' so you would cut out anyone using this library and Expo.

**Comment by mfrachet** [comment]
This is not a thing that I'm looking for with the lib :/
