### ISSUE TITLE
V3 Plans

### ISSUE THREAD

**Issue by mfrachet** [mfrachet/rn-placeholder#78]
I'm actually thinking of a V3 fully rewritten in typescript :D :D :D

**Comment by dsznajder** [comment]
@mfrachet Hi! Thanks for great package, in our team, we are heavily using you package, and I have 2 questions :P
Do you have some deadline for v3.0.0? 
Would you like to use `reanimated` for animations?

**Comment by mfrachet** [comment]
Hi!

Thanks for the kind words 😊 

I'm trying to find some time to work on it but I don't have that much 😓 .

My job takes me a lot of time and I can't invest myself as much as I want...

I'll keep you in touch as soon as I have more information about it :).

Concerning reanimated, I've not thought about it, but why not :)

**Comment by dsznajder** [comment]
@mfrachet If you have only plans for TS now, I probably can handle it this week :)

**Comment by mfrachet** [comment]
I'm actually working on a secrete piece of code that I will share soon. Obviously it's written in typescript, but with some breaking APIs...

But I think that you will like it 😄 😎

**Comment by dsznajder** [comment]
@mfrachet I've started some TS already :) I will eventually rebase it to your changes :)

**Comment by mfrachet** [comment]
I pushed it on github if you want review / play with it: https://github.com/mfrachet/rn-placeholder/pull/86

**Comment by mfrachet** [comment]
V3 alpha is now out! I'm closing this issue for now, feel free to reopen!

And tell me if you like this release or not 😊 .

Thanks for your help folks!

**Comment by VanHoutte** [comment]
@mfrachet 

First of all, really loving the library and looking forward to the new release and typescript!

Would it be possible to make the alpha available via npm?

**Comment by mfrachet** [comment]
It is ! 😊 https://www.npmjs.com/package/rn-placeholder

Thanks for the kind words 😄
