### ISSUE TITLE
suggest replacing 'width: 100%' with 'marginHorizontal' to make styles more flexible

### ISSUE THREAD

**Issue by runryan** [mfrachet/rn-placeholder#81]
When I use Line and Placeholder components, I find it's hard to custom their width due to `width: 100%` limitation. Sometimes we just tell a component its marginHorizontal to calculate its width automatically. So I suggest replacing `width: 100%` with `marginHorizontal:0` to make styles more flexible. 
I've submitted a [pull request](https://github.com/mfrachet/rn-placeholder/pull/80). It failed anyway.

**Comment by mfrachet** [comment]
Same as in the PR, thanks for the suggestion but I will probably keep the actual API 😊
