### ISSUE TITLE
Typescript definition is not available after npm install 

### ISSUE THREAD

**Issue by changLiuUNSW** [mfrachet/rn-placeholder#84]
I can see ```index.d.ts``` in the repo but it is not available after npm install.

Maybe it is not published yet?

**Comment by mfrachet** [comment]
It has not been published yet. Sorry for that 😞

**Comment by changLiuUNSW** [comment]
Thanks @mfrachet . Do you have ETA for it?

**Comment by mfrachet** [comment]
I'm actually having something good running locally. Need to make some small fixes + add a new readme, but I should probably push something visible in the week 😄

**Comment by mfrachet** [comment]
It's not on github => https://github.com/mfrachet/rn-placeholder/pull/86

**Comment by mfrachet** [comment]
[This is solved in v3 🎉](https://github.com/mfrachet/rn-placeholder/tree/master/lib) . Let me know if it works for you and reopen if needed 😊
