### ISSUE TITLE
Cannot use elevation, if used it will not trigger "shine" animation

### ISSUE THREAD

**Issue by winardis** [mfrachet/rn-placeholder#85]
![working](https://user-images.githubusercontent.com/48976564/60651396-4ef95680-9e70-11e9-903d-6eeba04643e6.gif)
![not working](https://user-images.githubusercontent.com/48976564/60651407-53257400-9e70-11e9-833a-13aacd4b8b32.gif)
Hi i wanted to ask is there a way to use elevation on with the "shine" animation, with elevation on the style of the view kind of blocked the "shine" to the back so the animation doesn't show.
I have tried it with "fade", it still works but as for "shine" it doesnt show at all 
this is the code i'm working with the issue i reported

`render() {
        return (
            <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
                <Placeholder
                    animation="shine"
                    isReady={false}
                    whenReadyRender={() =>
                        <FlatList
                            keyExtractor={this._keyExtractor}
                            data={this.props.universalsInbox}
                            renderItem={this.renderItem.bind(this)}
                            ListEmptyComponent={this.renderEmptyState.bind(this)} />
                    }
                >
                    <View style={{
                        backgroundColor: 'white',
                        borderRadius: 4,
                        shadowColor: "rgba(69, 91, 99, 0.16)",
                        shadowOffset: {
                            width: 0,
                            height: 4
                        },
                        shadowRadius: 4,
                        shadowOpacity: 1,
                        elevation: 4,
                        marginVertical: 10,
                        marginHorizontal: 20,
                        padding: 14
                    }}>
                        <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}>
                            <Text style={{ flex: 1 }}>Username</Text>
                            <Line style={{ flex: 0.15 }} />
                        </View>
                        <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}>
                            <Line width="45%" />
                            <Line width="45%" />
                        </View>
                        <View style={{ flexDirection: 'row' }}>
                            <Line style={{ flex: 0.35 }} />
                            <View style={{ flex: 0.2 }} />
                            <Line style={{ flex: 0.35 }} />
                        </View>
                    </View >
                </Placeholder>
            </View>
        );
    }`

**Comment by mfrachet** [comment]
Thank you for this! Can you provide a https://snack.expo.io/ so that I can hack / tweak on it? 😊

**Comment by username199327** [comment]
i'm sorry for the late reply i'll try, i have no experience with expo yet
because usually i use react-native cli, i'll try to :smile

**Comment by mfrachet** [comment]
I have provided a snack usage of elevation on the V3 => https://snack.expo.io/@mfrachet/84bb31 .

Let me know if it's okay for you 😊 . I'm closing this for now 😄
