### ISSUE TITLE
Wrong path of declaration file in package.json

### ISSUE THREAD

**Issue by Phecda** [mfrachet/rn-placeholder#89]
https://github.com/mfrachet/rn-placeholder/blob/d3696798a6291f1e9ec3916141a7d446d8795da9/package.json#L5

Hi! My VSCode complains that declaration file is not found, so I think this should be `lib/index.d.ts` .

**Comment by mfrachet** [comment]
Woops! Thanks for the report!

https://github.com/mfrachet/rn-placeholder/pull/90 has fixed it and it's now published on npm under alpha-3 => https://www.npmjs.com/package/rn-placeholder

Let me know if it fixes this for you 😊
