### ISSUE TITLE
Custom Animations - alpha v3

### ISSUE THREAD

**Issue by VanHoutte** [mfrachet/rn-placeholder#91]
Hi

I'm testing the alpha version and it works really well. 

I have 2 PlaceholderLines with different width but I want the shine animation to start at the exact same time and end at the same time and cross the same distance. The issue is that I cannot use a ShineOverlay since a white block is rendered on top of both views and I use a blue background.

I was thinking of creating a custom animation but I don't have access to the Provider. Any idea on how to create a custom animation?

Thanks in advance!

**Comment by mfrachet** [comment]
Hi,

Actually, this issue is linked to the other one https://github.com/mfrachet/rn-placeholder/issues/73 and I don't have plans for now to fix this :(.

I'm looking for solution.

And the other point concerning accessing the context, it's because I forgot to export it in the main file 😓 

I'll try to do it soon 😅

**Comment by VanHoutte** [comment]
Well if you could export the context and provider, i might be able to come up with something. If so, I'll create a PR.

**Comment by mfrachet** [comment]
Sorry for being that late. It's on master and available on npm https://github.com/mfrachet/rn-placeholder/blob/master/src/index.tsx#L9

**Comment by mfrachet** [comment]
I close this for now, feel free to reopen 😊

**Comment by VanHoutte** [comment]
Thanks for the update!

Not sure if I will look into this, i'm switching jobs and going back to full time iOS development.

Anyway, keep up the good work!

**Comment by mfrachet** [comment]
I wish you a great adventure and thanks for your help here 😊
