### ISSUE TITLE
How to show horizontal items?

### ISSUE THREAD

**Issue by minhchienwikipedia** [mfrachet/rn-placeholder#92]
Hi guys, I have an issue about show many items with horizontal style, but seems it's not working.
I had tried like this.
```
<Placeholder
 Animation={Fade}
>
         <PlaceholderLine width={70} height={30} style={containerStyles.section} />
         <View style={{ flexDirection: "row" }}>
                 <PlaceholderMedia style={styles.placeholderItem} />
                 <PlaceholderMedia style={styles.placeholderItem} />
                 <PlaceholderMedia style={styles.placeholderItem} />
        </View>
</Placeholder>
```
 And I had tried use `<Placeholder>` instead of `<View>` but it's still not working. It's not showing anything. Can you help me?

**Comment by mfrachet** [comment]
Hi 😄 

Do you have some mockups of what you want to achieve? Maybe I can take a look and check what's feasible for the need 😊 

Thanks 😊

**Comment by minhchienwikipedia** [comment]
@mfrachet  I wanna try something like that
![Demo](https://user-images.githubusercontent.com/20647079/62095457-b1484a00-b2aa-11e9-9997-2848a0016e9f.jpg)

**Comment by mfrachet** [comment]
Hi 😊 

Let me know if something like https://github.com/mfrachet/rn-placeholder/pull/94 would make the job as you wish it to do 😊

**Comment by mfrachet** [comment]
It seems that you can now do this and it has been published on NPM :)

You can give it a try on https://snack.expo.io/@mfrachet/rn-placeholder-v3 😊

**Comment by mfrachet** [comment]
I close this for now, feel free to reopen!

**Comment by minhchienwikipedia** [comment]
@mfrachet It's work as well, thank you so much :D
