### ISSUE TITLE
How to use with react-native-web

### ISSUE THREAD

**Issue by jasonjlock** [mfrachet/rn-placeholder#96]
Everything works great with React Native, but when I try to add rn-placeholder (2.0.0) to an app using react-native-web (0.11.2) I run into the following error:
```javascript
/code/app/node_modules/rn-placeholder/src/index.js:1
import { Placeholder } from './placeholder/placeholder';
       ^
SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
```
Is there anything special I need to add to my .babelrc?  Here's my .babelrc: 
```javascript
{
  "plugins": [
    ["react-native-web", {commonjs: true}],
    ["module-resolver", {
      "alias": {
        "^react-native$": "react-native-web",
        "react-native-web/dist/cjs/exports/Modal": "modal-enhanced-react-native-web",
      }
    }],
    ["@babel/plugin-proposal-class-properties"]
  ],
  "presets": ["next/babel"]
}

```
Thank you for your help!

**Comment by mfrachet** [comment]
I've just made a simple test using `create-react-app` and it works perfectly: 

<img width="1680" alt="Screenshot 2019-08-05 at 8 35 11 AM" src="https://user-images.githubusercontent.com/3874873/62465043-04fbdd00-b75c-11e9-97e4-648e6562442e.png">

Maybe it's a configuration problem?

**Comment by mfrachet** [comment]
The project now owns a `example-web` folder with a usage of rn-placeholder using react-native-web.

It's also hosted on gh-pages: https://mfrachet.github.io/rn-placeholder/

**Comment by jasonjlock** [comment]
Thank you for the example! It's most definitely a configuration issue on my end. Thanks again for your time.

**Comment by mfrachet** [comment]
No problems ! Happy coding 😊!
